name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        command: server /data
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest boto3 requests
        pip install -e .
    - name: Wait for MinIO
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:9000/minio/health/live; then
            echo "MinIO is up"; break;
          fi
          sleep 2
        done
    - name: Run integration tests
      env:
        S3_ENDPOINT: http://localhost:9000
        S3_ACCESS_KEY: minioadmin
        S3_SECRET_KEY: minioadmin
        S3_BUCKET: logflow-ci
        S3_REGION: us-east-1
      run: pytest tests/integration --maxfail=3 --disable-warnings -v
